# Generated by Django 5.1.3 on 2024-12-20 23:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True, help_text='Oluşturulma tarihi')),
                ('updatedAt', models.DateTimeField(auto_now=True, help_text='Son güncelleme tarihi')),
                ('questionText', models.TextField(verbose_name='Soru Metni')),
                ('questionType', models.CharField(choices=[('text', 'Metin Yanıt'), ('rating', 'Puanlama'), ('multiple_choice', 'Çoktan Seçmeli'), ('single_choice', 'Tek Seçimli')], default='text', max_length=50, verbose_name='Soru Tipi')),
                ('site', models.ForeignKey(help_text='Bu kaydın ait olduğu siteyi belirtir.', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='sites.site')),
            ],
            options={
                'verbose_name': 'Soru',
                'verbose_name_plural': 'Sorular',
                'db_table': 'solosurvey_questions',
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True, help_text='Oluşturulma tarihi')),
                ('updatedAt', models.DateTimeField(auto_now=True, help_text='Son güncelleme tarihi')),
                ('choiceText', models.CharField(max_length=255, verbose_name='Seçenek Metni')),
                ('site', models.ForeignKey(help_text='Bu kaydın ait olduğu siteyi belirtir.', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='sites.site')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='solosurvey.question')),
            ],
            options={
                'verbose_name': 'Seçenek',
                'verbose_name_plural': 'Seçenekler',
                'db_table': 'solosurvey_choices',
            },
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True, help_text='Oluşturulma tarihi')),
                ('updatedAt', models.DateTimeField(auto_now=True, help_text='Son güncelleme tarihi')),
                ('title', models.CharField(max_length=255, verbose_name='Anket Başlığı')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Anket Açıklaması')),
                ('startDate', models.DateTimeField(blank=True, null=True, verbose_name='Başlangıç Tarihi')),
                ('endDate', models.DateTimeField(blank=True, null=True, verbose_name='Bitiş Tarihi')),
                ('isActive', models.BooleanField(default=True, verbose_name='Aktif Mi?')),
                ('rewardPoints', models.PositiveIntegerField(default=0, verbose_name='Ödül Puanı')),
                ('site', models.ForeignKey(help_text='Bu kaydın ait olduğu siteyi belirtir.', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='sites.site')),
            ],
            options={
                'verbose_name': 'Anket',
                'verbose_name_plural': 'Anketler',
                'db_table': 'solosurvey_surveys',
            },
        ),
        migrations.AddField(
            model_name='question',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='solosurvey.survey'),
        ),
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True, help_text='Oluşturulma tarihi')),
                ('updatedAt', models.DateTimeField(auto_now=True, help_text='Son güncelleme tarihi')),
                ('anonymousIdentifier', models.CharField(blank=True, max_length=255, null=True, verbose_name='Anonim Kimlik')),
                ('completedAt', models.DateTimeField(auto_now_add=True, verbose_name='Tamamlanma Tarihi')),
                ('respondent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Cevaplayan Kullanıcı')),
                ('site', models.ForeignKey(help_text='Bu kaydın ait olduğu siteyi belirtir.', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='sites.site')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='solosurvey.survey')),
            ],
            options={
                'verbose_name': 'Anket Yanıtı',
                'verbose_name_plural': 'Anket Yanıtları',
                'db_table': 'solosurvey_responses',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True, help_text='Oluşturulma tarihi')),
                ('updatedAt', models.DateTimeField(auto_now=True, help_text='Son güncelleme tarihi')),
                ('answerText', models.TextField(blank=True, null=True, verbose_name='Metin Yanıt')),
                ('numericValue', models.IntegerField(blank=True, null=True, verbose_name='Sayısal Değer (örn. rating)')),
                ('site', models.ForeignKey(help_text='Bu kaydın ait olduğu siteyi belirtir.', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='sites.site')),
                ('selectedChoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_answers', to='solosurvey.choice', verbose_name='Seçilen Seçenek')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solosurvey.question')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='solosurvey.surveyresponse')),
            ],
            options={
                'verbose_name': 'Cevap',
                'verbose_name_plural': 'Cevaplar',
                'db_table': 'solosurvey_answers',
            },
        ),
        migrations.CreateModel(
            name='SurveyTrigger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True, help_text='Oluşturulma tarihi')),
                ('updatedAt', models.DateTimeField(auto_now=True, help_text='Son güncelleme tarihi')),
                ('triggerEvent', models.CharField(max_length=255, verbose_name='Tetikleyici Olay')),
                ('sendEmail', models.BooleanField(default=False, verbose_name='E-posta Gönder?')),
                ('sendSms', models.BooleanField(default=False, verbose_name='SMS Gönder?')),
                ('sendWhatsapp', models.BooleanField(default=False, verbose_name='WhatsApp Mesajı Gönder?')),
                ('delayHours', models.PositiveIntegerField(default=0, verbose_name='Gönderim Gecikmesi (saat)')),
                ('site', models.ForeignKey(help_text='Bu kaydın ait olduğu siteyi belirtir.', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='sites.site')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triggers', to='solosurvey.survey')),
            ],
            options={
                'verbose_name': 'Anket Tetikleyici',
                'verbose_name_plural': 'Anket Tetikleyiciler',
                'db_table': 'solosurvey_triggers',
            },
        ),
    ]
