# Generated by Django 5.1.3 on 2024-12-03 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleApplicationsIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True, help_text='Oluşturulma tarihi')),
                ('updatedAt', models.DateTimeField(auto_now=True, help_text='Son güncelleme tarihi')),
                ('applicationType', models.CharField(choices=[('google_webmasters', 'Google Webmasters'), ('google_analytics', 'Google Analytics'), ('google_tag_manager', 'Google Tag Manager'), ('google_adsense', 'Google Adsense')], help_text='Google uygulama türünü belirtir (ör. Google Analytics, Tag Manager, Adsense).', max_length=50, verbose_name='Uygulama Türü')),
                ('applicationCode', models.TextField(help_text='Google uygulaması tarafından sağlanan entegrasyon kodu.', verbose_name='Uygulama Kodu')),
                ('site', models.ForeignKey(help_text='Bu kaydın ait olduğu siteyi belirtir.', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='sites.site')),
            ],
            options={
                'verbose_name': 'Google Uygulama Entegrasyonu',
                'verbose_name_plural': 'Google Uygulama Entegrasyonları',
            },
        ),
    ]
