# Generated by Django 5.1.3 on 2024-12-03 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True, help_text='Oluşturulma tarihi')),
                ('updatedAt', models.DateTimeField(auto_now=True, help_text='Son güncelleme tarihi')),
                ('siteName', models.CharField(help_text='Sitenin görünen adını belirtin.', max_length=255, verbose_name='Site Adı')),
                ('metaTitle', models.CharField(help_text='SEO için sitenin meta başlığını belirtin.', max_length=255, verbose_name='Meta Başlık')),
                ('metaDescription', models.TextField(help_text='SEO için sitenin meta açıklamasını belirtin.', verbose_name='Meta Açıklama')),
                ('logo', models.ImageField(help_text='Site logosunu yükleyin.', upload_to='logos/', verbose_name='Logo')),
                ('cookiePolicy', models.TextField(help_text='Sitenin çerez politikasını burada belirtin.', verbose_name='Çerez Politikası')),
                ('privacyPolicy', models.TextField(help_text='Sitenin gizlilik politikasını burada belirtin.', verbose_name='Gizlilik Politikası')),
                ('termsOfUse', models.TextField(help_text='Sitenin kullanım koşullarını burada belirtin.', verbose_name='Kullanım Koşulları')),
                ('phone', models.CharField(help_text='İletişim için sabit telefon numarasını girin.', max_length=15, verbose_name='Telefon')),
                ('gsm', models.CharField(help_text='İletişim için mobil telefon numarasını girin.', max_length=15, verbose_name='GSM')),
                ('email', models.EmailField(help_text='İletişim için e-posta adresini girin.', max_length=254, verbose_name='E-posta')),
                ('address', models.TextField(help_text='İletişim için adres bilgilerini girin.', verbose_name='Adres')),
                ('googleMap', models.URLField(help_text='Google Haritalar bağlantısını girin.', verbose_name='Google Harita')),
                ('aboutUs', models.TextField(help_text='Sitenin hakkımızda metnini buraya yazın.', verbose_name='Hakkımızda')),
                ('kvkkAgreement', models.TextField(help_text='KVKK ile ilgili sözleşme metnini burada belirtin.', verbose_name='KVKK Sözleşmesi')),
                ('site', models.ForeignKey(help_text='Bu kaydın ait olduğu siteyi belirtir.', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='sites.site')),
            ],
            options={
                'verbose_name': 'Site Ayarları',
                'verbose_name_plural': 'Site Ayarları',
            },
        ),
    ]
