# Generated by Django 5.1.3 on 2024-12-04 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_sitesettings'),
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmtpSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True, help_text='Oluşturulma tarihi')),
                ('updatedAt', models.DateTimeField(auto_now=True, help_text='Son güncelleme tarihi')),
                ('emailAddress', models.EmailField(max_length=255, verbose_name='Gönderici E-posta Adresi')),
                ('smtpServer', models.CharField(max_length=255, verbose_name='SMTP Sunucusu')),
                ('smtpPort', models.PositiveIntegerField(default=587, verbose_name='SMTP Portu')),
                ('username', models.CharField(max_length=255, verbose_name='Kullanıcı Adı')),
                ('password', models.CharField(max_length=255, verbose_name='Şifre')),
                ('useTls', models.BooleanField(default=True, verbose_name='TLS Kullanımı')),
                ('useSsl', models.BooleanField(default=False, verbose_name='SSL Kullanımı')),
                ('site', models.ForeignKey(help_text='Bu kaydın ait olduğu siteyi belirtir.', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='sites.site')),
            ],
            options={
                'verbose_name': 'SMTP Ayarı',
                'verbose_name_plural': 'SMTP Ayarları',
                'db_table': 'smtp_settings',
            },
        ),
    ]
