# Generated by Django 5.1.3 on 2024-12-04 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_smtpsettings'),
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmsSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True, help_text='Oluşturulma tarihi')),
                ('updatedAt', models.DateTimeField(auto_now=True, help_text='Son güncelleme tarihi')),
                ('url', models.URLField(max_length=500, verbose_name='SMS API URL')),
                ('username', models.CharField(max_length=255, verbose_name='Kullanıcı Adı')),
                ('password', models.CharField(max_length=255, verbose_name='Şifre')),
                ('kontorMiktari', models.PositiveIntegerField(default=0, verbose_name='Kontör Miktarı')),
                ('site', models.ForeignKey(help_text='Bu kaydın ait olduğu siteyi belirtir.', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='sites.site')),
            ],
            options={
                'verbose_name': 'SMS Ayarı',
                'verbose_name_plural': 'SMS Ayarları',
                'db_table': 'sms_settings',
            },
        ),
    ]
