# Generated by Django 5.1.3 on 2024-12-04 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_whatsappsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappsettings',
            name='kontorMiktari',
            field=models.PositiveIntegerField(default=0, verbose_name='Kontör Miktarı'),
        ),
    ]
