# Generated by Django 5.1.3 on 2024-12-20 23:36

import django.db.models.deletion
import soloblog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True, help_text='Oluşturulma tarihi')),
                ('updatedAt', models.DateTimeField(auto_now=True, help_text='Son güncelleme tarihi')),
                ('position', models.CharField(choices=[('article', 'Makale İçi'), ('sidebar', 'Side Bar'), ('topbar', 'Top Bar'), ('homepage', 'Anasayfa'), ('other', 'Diğer')], help_text='Reklamın gösterileceği alanı belirtir.', max_length=50, verbose_name='Reklam Alanı')),
                ('image', models.ImageField(help_text='Bu alana reklam görselini yükleyin.', upload_to='advertisements/', verbose_name='Reklam Görseli')),
                ('link', models.URLField(blank=True, help_text='Reklama tıklanınca gidilecek URL.', null=True, verbose_name='Reklam Linki')),
                ('site', models.ForeignKey(help_text='Bu kaydın ait olduğu siteyi belirtir.', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='sites.site')),
            ],
            options={
                'verbose_name': 'Reklam',
                'verbose_name_plural': 'Reklamlar',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True, help_text='Oluşturulma tarihi')),
                ('updatedAt', models.DateTimeField(auto_now=True, help_text='Son güncelleme tarihi')),
                ('categoryName', models.CharField(max_length=255, verbose_name='Kategori Adı')),
                ('categoryDescription', models.TextField(verbose_name='Kategori Açıklaması')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL Yolu')),
                ('meta', models.TextField(blank=True, null=True, verbose_name='Meta Veriler')),
                ('metaDescription', models.TextField(blank=True, null=True, verbose_name='Meta Açıklaması')),
                ('order', models.IntegerField(default=0, verbose_name='Sıra')),
                ('categoryImage', models.ImageField(blank=True, null=True, upload_to='category_images/', verbose_name='Kategori Görseli')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='soloblog.category', verbose_name='Üst Kategori')),
                ('site', models.ForeignKey(help_text='Bu kaydın ait olduğu siteyi belirtir.', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='sites.site')),
            ],
            options={
                'verbose_name': 'Kategori',
                'verbose_name_plural': 'Kategoriler',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True, help_text='Oluşturulma tarihi')),
                ('updatedAt', models.DateTimeField(auto_now=True, help_text='Son güncelleme tarihi')),
                ('title', models.CharField(max_length=255, verbose_name='Başlık')),
                ('content', models.TextField(verbose_name='İçerik')),
                ('featured', models.BooleanField(default=False, verbose_name='Öne Çıkan')),
                ('slider', models.BooleanField(default=False, verbose_name='Slider Gösterimi')),
                ('active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('slug', models.SlugField(max_length=255, verbose_name='URL Yolu')),
                ('counter', models.IntegerField(default=0, verbose_name='Sayaç')),
                ('meta', models.TextField(blank=True, null=True, verbose_name='Meta Veriler')),
                ('metaDescription', models.TextField(blank=True, null=True, verbose_name='Meta Açıklaması')),
                ('publicationDate', models.DateTimeField(auto_now_add=True, verbose_name='Yayınlanma Tarihi')),
                ('image', models.ImageField(blank=True, null=True, upload_to='article_images/', verbose_name='Makale Resmi')),
                ('site', models.ForeignKey(help_text='Bu kaydın ait olduğu siteyi belirtir.', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='sites.site')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soloblog.category', verbose_name='Kategori')),
            ],
            options={
                'verbose_name': 'Makale',
                'verbose_name_plural': 'Makaleler',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True, help_text='Oluşturulma tarihi')),
                ('updatedAt', models.DateTimeField(auto_now=True, help_text='Son güncelleme tarihi')),
                ('approved', models.BooleanField(default=False, verbose_name='Onay Durumu')),
                ('firstName', models.CharField(max_length=255, verbose_name='Ad')),
                ('lastName', models.CharField(max_length=255, verbose_name='Soyad')),
                ('email', models.EmailField(max_length=254, verbose_name='E-posta')),
                ('phoneNumber', models.CharField(max_length=15, verbose_name='Telefon Numarası')),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1, verbose_name='Yıldız Puanı')),
                ('content', models.TextField(verbose_name='Yorum')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Adresi')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='soloblog.article', verbose_name='Makale')),
                ('site', models.ForeignKey(help_text='Bu kaydın ait olduğu siteyi belirtir.', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='sites.site')),
            ],
            options={
                'verbose_name': 'Yorum',
                'verbose_name_plural': 'Yorumlar',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True, help_text='Oluşturulma tarihi')),
                ('updatedAt', models.DateTimeField(auto_now=True, help_text='Son güncelleme tarihi')),
                ('imagePath', models.ImageField(upload_to=soloblog.models.get_image_upload_path, verbose_name='Resim Yolu')),
                ('resizedImage', models.ImageField(blank=True, null=True, upload_to=soloblog.models.get_image_upload_path, verbose_name='Boyutlandırılmış Resim')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='soloblog.article', verbose_name='Makale')),
                ('site', models.ForeignKey(help_text='Bu kaydın ait olduğu siteyi belirtir.', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='sites.site')),
            ],
            options={
                'verbose_name': 'Makale Resim',
                'verbose_name_plural': 'Makale Resimleri',
            },
        ),
        migrations.CreateModel(
            name='PopupAd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='HTML veya metin içerik.', verbose_name='Reklam İçeriği')),
                ('isActive', models.BooleanField(default=True, help_text='Reklam aktif mi?', verbose_name='Aktif')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updatedAt', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('sites', models.ManyToManyField(help_text='Bu reklamın gösterileceği siteler.', related_name='popup_ads', to='sites.site', verbose_name='Bağlı Siteler')),
            ],
            options={
                'verbose_name': 'Pop-up Reklam',
                'verbose_name_plural': 'Pop-up Reklamları',
                'ordering': ['-createdAt'],
            },
        ),
        migrations.CreateModel(
            name='VisitorAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True, help_text='Oluşturulma tarihi')),
                ('updatedAt', models.DateTimeField(auto_now=True, help_text='Son güncelleme tarihi')),
                ('visit_type', models.CharField(choices=[('homepage', 'Ana Sayfa'), ('article', 'Makale')], help_text='Ziyaretin ana sayfa mı yoksa makale mi olduğunu belirtir.', max_length=20, verbose_name='Ziyaret Tipi')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP Adresi')),
                ('user_agent', models.TextField(verbose_name='Kullanıcı Tarayıcısı')),
                ('referer', models.URLField(blank=True, null=True, verbose_name='Yönlendiren URL')),
                ('visit_date', models.DateTimeField(auto_now_add=True, verbose_name='Ziyaret Tarihi')),
                ('country', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ülke')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Şehir')),
                ('device_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Cihaz Türü')),
                ('operating_system', models.CharField(blank=True, max_length=50, null=True, verbose_name='İşletim Sistemi')),
                ('browser', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tarayıcı')),
                ('session_duration', models.IntegerField(blank=True, null=True, verbose_name='Oturum Süresi (saniye)')),
                ('is_bounce', models.BooleanField(default=False, help_text='Ziyaret hemen çıkıldı mı?', verbose_name='Bounce Durumu')),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visitor_analytics', to='soloblog.article', verbose_name='Makale')),
                ('site', models.ForeignKey(help_text='Bu kaydın ait olduğu siteyi belirtir.', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='sites.site')),
            ],
            options={
                'verbose_name': 'Ziyaretçi İstatistiği',
                'verbose_name_plural': 'Ziyaretçi İstatistikleri',
            },
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['site'], name='soloblog_ca_site_id_00a36f_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['category'], name='soloblog_ar_categor_406b40_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['site'], name='soloblog_ar_site_id_d34fb2_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['slug'], name='soloblog_ar_slug_47d1ec_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['title'], name='soloblog_ar_title_3ed183_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['publicationDate'], name='soloblog_ar_publica_c87c1b_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['site', 'category'], name='soloblog_ar_site_id_27c47e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='article',
            unique_together={('site', 'slug')},
        ),
        migrations.AddIndex(
            model_name='visitoranalytics',
            index=models.Index(fields=['site'], name='soloblog_vi_site_id_038723_idx'),
        ),
        migrations.AddIndex(
            model_name='visitoranalytics',
            index=models.Index(fields=['article'], name='soloblog_vi_article_c1ef94_idx'),
        ),
        migrations.AddIndex(
            model_name='visitoranalytics',
            index=models.Index(fields=['visit_date'], name='soloblog_vi_visit_d_4bd6bb_idx'),
        ),
    ]
