# Generated by Django 5.1.3 on 2024-12-22 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soloblog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='phoneNumber',
            field=models.CharField(max_length=30, verbose_name='Telefon Numarası'),
        ),
    ]
