# Generated by Django 5.1.3 on 2024-12-03 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('soloblog', '0007_popupad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True, help_text='Oluşturulma tarihi')),
                ('updatedAt', models.DateTimeField(auto_now=True, help_text='Son güncelleme tarihi')),
                ('position', models.CharField(choices=[('article', 'Makale İçi'), ('sidebar', 'Side Bar'), ('topbar', 'Top Bar'), ('homepage', 'Anasayfa'), ('other', 'Diğer')], help_text='Reklamın gösterileceği alanı belirtir.', max_length=50, verbose_name='Reklam Alanı')),
                ('image', models.ImageField(help_text='Bu alana reklam görselini yükleyin.', upload_to='advertisements/', verbose_name='Reklam Görseli')),
                ('link', models.URLField(blank=True, help_text='Reklama tıklanınca gidilecek URL.', null=True, verbose_name='Reklam Linki')),
                ('site', models.ForeignKey(help_text='Bu kaydın ait olduğu siteyi belirtir.', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='sites.site')),
            ],
            options={
                'verbose_name': 'Reklam',
                'verbose_name_plural': 'Reklamlar',
            },
        ),
    ]
