# Generated by Django 5.1.3 on 2024-12-03 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('soloblog', '0008_advertisement'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True, help_text='Oluşturulma tarihi')),
                ('updatedAt', models.DateTimeField(auto_now=True, help_text='Son güncelleme tarihi')),
                ('visit_type', models.CharField(choices=[('homepage', 'Ana Sayfa'), ('article', 'Makale')], help_text='Ziyaretin ana sayfa mı yoksa makale mi olduğunu belirtir.', max_length=20, verbose_name='Ziyaret Tipi')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP Adresi')),
                ('user_agent', models.TextField(verbose_name='Kullanıcı Tarayıcısı')),
                ('referer', models.URLField(blank=True, null=True, verbose_name='Yönlendiren URL')),
                ('visit_date', models.DateTimeField(auto_now_add=True, verbose_name='Ziyaret Tarihi')),
                ('country', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ülke')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Şehir')),
                ('device_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Cihaz Türü')),
                ('operating_system', models.CharField(blank=True, max_length=50, null=True, verbose_name='İşletim Sistemi')),
                ('browser', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tarayıcı')),
                ('session_duration', models.IntegerField(blank=True, null=True, verbose_name='Oturum Süresi (saniye)')),
                ('is_bounce', models.BooleanField(default=False, help_text='Ziyaret hemen çıkıldı mı?', verbose_name='Bounce Durumu')),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visitor_analytics', to='soloblog.article', verbose_name='Makale')),
                ('site', models.ForeignKey(help_text='Bu kaydın ait olduğu siteyi belirtir.', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='sites.site')),
            ],
            options={
                'verbose_name': 'Ziyaretçi İstatistiği',
                'verbose_name_plural': 'Ziyaretçi İstatistikleri',
            },
        ),
    ]
