# Generated by Django 5.1.3 on 2024-12-04 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('soloblog', '0010_visitoranalytics_soloblog_vi_site_id_038723_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['site'], name='soloblog_ar_site_id_d34fb2_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['title'], name='soloblog_ar_title_3ed183_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['slug'], name='soloblog_ar_slug_47d1ec_idx'),
        ),
    ]
