# Generated by Django 5.1.3 on 2024-12-04 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('soloblog', '0011_article_soloblog_ar_site_id_d34fb2_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['category'], name='soloblog_ar_categor_406b40_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['publicationDate'], name='soloblog_ar_publica_c87c1b_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['site', 'category'], name='soloblog_ar_site_id_27c47e_idx'),
        ),
    ]
