# Generated by Django 5.1.3 on 2024-12-04 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('soloblog', '0012_article_soloblog_ar_categor_406b40_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['site'], name='soloblog_ca_site_id_00a36f_idx'),
        ),
    ]
