# Generated by Django 5.1.3 on 2024-12-21 09:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_bio'),
        ('sites', '0002_alter_domain_unique'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True, help_text='Oluşturulma tarihi')),
                ('updatedAt', models.DateTimeField(auto_now=True, help_text='Son güncelleme tarihi')),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('USERS', 'Users'), ('OPERATION', 'Operation')], default='USERS', help_text='Kullanıcının bu site üzerindeki rolü.', max_length=20)),
                ('site', models.ForeignKey(help_text='Bu kaydın ait olduğu siteyi belirtir.', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='sites.site')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userSites', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Kullanıcı-Site İlişkisi',
                'verbose_name_plural': 'Kullanıcı-Site İlişkileri',
                'unique_together': {('user', 'site')},
            },
        ),
    ]
