# Generated by Django 5.1.3 on 2024-12-21 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_bio'),
        ('solosite', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siterole',
            name='createdAt',
        ),
        migrations.RemoveField(
            model_name='siterole',
            name='site',
        ),
        migrations.RemoveField(
            model_name='siterole',
            name='updatedAt',
        ),
        migrations.AlterField(
            model_name='siterole',
            name='code',
            field=models.CharField(help_text='Benzersiz rol kodu', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='siterole',
            name='name',
            field=models.CharField(help_text='Rol adı (admin, manager, staff, vb.)', max_length=50),
        ),
        migrations.AlterField(
            model_name='siteuserrole',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignedProfiles', to='solosite.siterole'),
        ),
        migrations.AlterField(
            model_name='siteuserrole',
            name='userProfile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solositeRoles', to='accounts.userprofile'),
        ),
    ]
