# Generated by Django 5.1.3 on 2024-11-30 19:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Modül Adı')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Modül Açıklaması')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updatedAt', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
            ],
            options={
                'verbose_name': 'Modül',
                'verbose_name_plural': 'Modüller',
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Site Adı')),
                ('domain', models.CharField(max_length=255, unique=True, verbose_name='Site Domain')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updatedAt', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sites', to='soloaccounting.module', verbose_name='Bağlı Modül')),
            ],
            options={
                'verbose_name': 'Site',
                'verbose_name_plural': 'Siteler',
            },
        ),
        migrations.CreateModel(
            name='UserSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userSites', to='soloaccounting.site', verbose_name='Site')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userSites', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Kullanıcı-Site İlişkisi',
                'verbose_name_plural': 'Kullanıcı-Site İlişkileri',
            },
        ),
    ]
