# Generated by Django 5.1.3 on 2024-12-02 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soloaccounting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='companyName',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Şirket/Kuruluş Adı'),
        ),
    ]
