# Generated by Django 5.1.3 on 2024-11-30 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('soloaccounting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersite',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userSites', to='sites.site', verbose_name='Site'),
        ),
        migrations.CreateModel(
            name='SiteModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='siteModules', to='soloaccounting.module', verbose_name='Modül')),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='module', to='sites.site', verbose_name='Site')),
            ],
            options={
                'verbose_name': 'Site Modülü',
                'verbose_name_plural': 'Site Modülleri',
            },
        ),
        migrations.DeleteModel(
            name='Site',
        ),
    ]
