# Generated by Django 5.1.3 on 2024-12-02 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('soloaccounting', '0002_customuser_companyname'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtendedSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updatedAt', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('isActive', models.BooleanField(default=True, verbose_name='active')),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extended_site', to='sites.site')),
            ],
            options={
                'verbose_name': 'extended site',
                'verbose_name_plural': 'extended sites',
            },
        ),
    ]
