# Generated by Django 5.1.3 on 2024-11-30 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soloaccounting', '0003_operatingsystem_customsiteconfiguration_mailserver_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dnsserver',
            name='site',
        ),
        migrations.RemoveField(
            model_name='mailserver',
            name='site',
        ),
        migrations.RemoveField(
            model_name='sqlserver',
            name='site',
        ),
        migrations.RemoveField(
            model_name='webserver',
            name='site',
        ),
    ]
