# Generated by Django 5.1.3 on 2024-12-03 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('soloaccounting', '0003_extendedsite'),
    ]

    operations = [
        migrations.AddField(
            model_name='dnsserver',
            name='site',
            field=models.ForeignKey(default=1, help_text='Bu kaydın ait olduğu siteyi belirtir.', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='sites.site'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mailserver',
            name='site',
            field=models.ForeignKey(default=1, help_text='Bu kaydın ait olduğu siteyi belirtir.', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='sites.site'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='module',
            name='site',
            field=models.ForeignKey(default=1, help_text='Bu kaydın ait olduğu siteyi belirtir.', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='sites.site'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='operatingsystem',
            name='site',
            field=models.ForeignKey(default=1, help_text='Bu kaydın ait olduğu siteyi belirtir.', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='sites.site'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='site',
            field=models.ForeignKey(default=1, help_text='Bu kaydın ait olduğu siteyi belirtir.', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='sites.site'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='site',
            field=models.ForeignKey(default=1, help_text='Bu kaydın ait olduğu siteyi belirtir.', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='sites.site'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sqlserver',
            name='site',
            field=models.ForeignKey(default=1, help_text='Bu kaydın ait olduğu siteyi belirtir.', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='sites.site'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usersite',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True, help_text='Son güncelleme tarihi'),
        ),
        migrations.AddField(
            model_name='webserver',
            name='site',
            field=models.ForeignKey(default=1, help_text='Bu kaydın ait olduğu siteyi belirtir.', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='sites.site'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customsiteconfiguration',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, help_text='Oluşturulma tarihi'),
        ),
        migrations.AlterField(
            model_name='customsiteconfiguration',
            name='site',
            field=models.ForeignKey(help_text='Bu kaydın ait olduğu siteyi belirtir.', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='sites.site'),
        ),
        migrations.AlterField(
            model_name='customsiteconfiguration',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True, help_text='Son güncelleme tarihi'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='site',
            field=models.ForeignKey(blank=True, help_text='Bu kullanıcının hangi siteye ait olduğunu belirtir.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='sites.site', verbose_name='Site'),
        ),
        migrations.AlterField(
            model_name='dnsserver',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, help_text='Oluşturulma tarihi'),
        ),
        migrations.AlterField(
            model_name='dnsserver',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True, help_text='Son güncelleme tarihi'),
        ),
        migrations.AlterField(
            model_name='mailserver',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, help_text='Oluşturulma tarihi'),
        ),
        migrations.AlterField(
            model_name='mailserver',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True, help_text='Son güncelleme tarihi'),
        ),
        migrations.AlterField(
            model_name='module',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, help_text='Oluşturulma tarihi'),
        ),
        migrations.AlterField(
            model_name='module',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True, help_text='Son güncelleme tarihi'),
        ),
        migrations.AlterField(
            model_name='operatingsystem',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, help_text='Oluşturulma tarihi'),
        ),
        migrations.AlterField(
            model_name='operatingsystem',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True, help_text='Son güncelleme tarihi'),
        ),
        migrations.AlterField(
            model_name='product',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, help_text='Oluşturulma tarihi'),
        ),
        migrations.AlterField(
            model_name='product',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True, help_text='Son güncelleme tarihi'),
        ),
        migrations.AlterField(
            model_name='service',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, help_text='Oluşturulma tarihi'),
        ),
        migrations.AlterField(
            model_name='service',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True, help_text='Son güncelleme tarihi'),
        ),
        migrations.AlterField(
            model_name='sqlserver',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, help_text='Oluşturulma tarihi'),
        ),
        migrations.AlterField(
            model_name='sqlserver',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True, help_text='Son güncelleme tarihi'),
        ),
        migrations.AlterField(
            model_name='usersite',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, help_text='Oluşturulma tarihi'),
        ),
        migrations.AlterField(
            model_name='usersite',
            name='site',
            field=models.ForeignKey(help_text='Bu kaydın ait olduğu siteyi belirtir.', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='sites.site'),
        ),
        migrations.AlterField(
            model_name='webserver',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, help_text='Oluşturulma tarihi'),
        ),
        migrations.AlterField(
            model_name='webserver',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True, help_text='Son güncelleme tarihi'),
        ),
    ]
