# Generated by Django 5.1.3 on 2024-11-30 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soloaccounting', '0004_remove_dnsserver_site_remove_mailserver_site_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailserver',
            name='operatingSystem',
        ),
        migrations.RemoveField(
            model_name='webserver',
            name='operatingSystem',
        ),
        migrations.RemoveField(
            model_name='sqlserver',
            name='operatingSystem',
        ),
        migrations.DeleteModel(
            name='DnsServer',
        ),
        migrations.DeleteModel(
            name='MailServer',
        ),
        migrations.DeleteModel(
            name='WebServer',
        ),
        migrations.DeleteModel(
            name='OperatingSystem',
        ),
        migrations.DeleteModel(
            name='SqlServer',
        ),
    ]
