# Generated by Django 5.1.3 on 2024-12-03 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('soloaccounting', '0004_dnsserver_site_mailserver_site_module_site_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='product',
        ),
        migrations.RemoveField(
            model_name='service',
            name='site',
        ),
        migrations.AlterField(
            model_name='siteurun',
            name='site',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='urunSite', to='sites.site', verbose_name='Site'),
        ),
        migrations.DeleteModel(
            name='Module',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
