# Generated by Django 5.1.3 on 2024-11-30 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soloaccounting', '0005_remove_mailserver_operatingsystem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperatingSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='İşletim Sistemi Adı')),
                ('version', models.CharField(blank=True, max_length=50, null=True, verbose_name='Versiyon')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updatedAt', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
            ],
            options={
                'verbose_name': 'İşletim Sistemi',
                'verbose_name_plural': 'İşletim Sistemleri',
            },
        ),
        migrations.CreateModel(
            name='MailServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(blank=True, max_length=255, null=True, verbose_name='Domain')),
                ('ns1', models.CharField(blank=True, max_length=255, null=True, verbose_name='NS1')),
                ('ns2', models.CharField(blank=True, max_length=255, null=True, verbose_name='NS2')),
                ('ipAddress1', models.GenericIPAddressField(blank=True, null=True, verbose_name='Mail Sunucusu IP 1')),
                ('ipAddress2', models.GenericIPAddressField(blank=True, null=True, verbose_name='Mail Sunucusu IP 2')),
                ('ipAddress3', models.GenericIPAddressField(blank=True, null=True, verbose_name='Mail Sunucusu IP 3')),
                ('ipAddress4', models.GenericIPAddressField(blank=True, null=True, verbose_name='Mail Sunucusu IP 4')),
                ('ipAddress5', models.GenericIPAddressField(blank=True, null=True, verbose_name='Mail Sunucusu IP 5')),
                ('username', models.CharField(blank=True, max_length=255, null=True, verbose_name='Kullanıcı Adı')),
                ('password', models.CharField(blank=True, max_length=255, null=True, verbose_name='Şifre')),
                ('paymentType', models.CharField(choices=[('Monthly', 'Aylık'), ('Yearly', 'Yıllık')], default='Monthly', max_length=10, verbose_name='Ödeme Tipi')),
                ('priceUsd', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Ücret (USD)')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updatedAt', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('operatingSystem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='soloaccounting.operatingsystem', verbose_name='İşletim Sistemi')),
            ],
            options={
                'verbose_name': 'Mail Sunucusu',
                'verbose_name_plural': 'Mail Sunucuları',
            },
        ),
        migrations.CreateModel(
            name='DnsServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(blank=True, max_length=255, null=True, verbose_name='Domain')),
                ('ns1', models.CharField(blank=True, max_length=255, null=True, verbose_name='NS1')),
                ('ns2', models.CharField(blank=True, max_length=255, null=True, verbose_name='NS2')),
                ('ipAddress1', models.GenericIPAddressField(blank=True, null=True, verbose_name='DNS Sunucusu IP 1')),
                ('ipAddress2', models.GenericIPAddressField(blank=True, null=True, verbose_name='DNS Sunucusu IP 2')),
                ('ipAddress3', models.GenericIPAddressField(blank=True, null=True, verbose_name='DNS Sunucusu IP 3')),
                ('ipAddress4', models.GenericIPAddressField(blank=True, null=True, verbose_name='DNS Sunucusu IP 4')),
                ('ipAddress5', models.GenericIPAddressField(blank=True, null=True, verbose_name='DNS Sunucusu IP 5')),
                ('username', models.CharField(blank=True, max_length=255, null=True, verbose_name='Kullanıcı Adı')),
                ('password', models.CharField(blank=True, max_length=255, null=True, verbose_name='Şifre')),
                ('paymentType', models.CharField(choices=[('Monthly', 'Aylık'), ('Yearly', 'Yıllık')], default='Monthly', max_length=10, verbose_name='Ödeme Tipi')),
                ('priceUsd', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Ücret (USD)')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updatedAt', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('operatingSystem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='soloaccounting.operatingsystem', verbose_name='İşletim Sistemi')),
            ],
            options={
                'verbose_name': 'DNS Sunucusu',
                'verbose_name_plural': 'DNS Sunucuları',
            },
        ),
        migrations.CreateModel(
            name='SqlServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(blank=True, max_length=255, null=True, verbose_name='Domain')),
                ('ns1', models.CharField(blank=True, max_length=255, null=True, verbose_name='NS1')),
                ('ns2', models.CharField(blank=True, max_length=255, null=True, verbose_name='NS2')),
                ('ipAddress1', models.GenericIPAddressField(blank=True, null=True, verbose_name='SQL Sunucusu IP 1')),
                ('ipAddress2', models.GenericIPAddressField(blank=True, null=True, verbose_name='SQL Sunucusu IP 2')),
                ('ipAddress3', models.GenericIPAddressField(blank=True, null=True, verbose_name='SQL Sunucusu IP 3')),
                ('ipAddress4', models.GenericIPAddressField(blank=True, null=True, verbose_name='SQL Sunucusu IP 4')),
                ('ipAddress5', models.GenericIPAddressField(blank=True, null=True, verbose_name='SQL Sunucusu IP 5')),
                ('username', models.CharField(blank=True, max_length=255, null=True, verbose_name='Kullanıcı Adı')),
                ('password', models.CharField(blank=True, max_length=255, null=True, verbose_name='Şifre')),
                ('paymentType', models.CharField(choices=[('Monthly', 'Aylık'), ('Yearly', 'Yıllık')], default='Monthly', max_length=10, verbose_name='Ödeme Tipi')),
                ('priceUsd', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Ücret (USD)')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updatedAt', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('operatingSystem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='soloaccounting.operatingsystem', verbose_name='İşletim Sistemi')),
            ],
            options={
                'verbose_name': 'SQL Sunucusu',
                'verbose_name_plural': 'SQL Sunucuları',
            },
        ),
        migrations.CreateModel(
            name='WebServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(blank=True, max_length=255, null=True, verbose_name='Domain')),
                ('ns1', models.CharField(blank=True, max_length=255, null=True, verbose_name='NS1')),
                ('ns2', models.CharField(blank=True, max_length=255, null=True, verbose_name='NS2')),
                ('ipAddress1', models.GenericIPAddressField(blank=True, null=True, verbose_name='Web Sunucusu IP 1')),
                ('ipAddress2', models.GenericIPAddressField(blank=True, null=True, verbose_name='Web Sunucusu IP 2')),
                ('ipAddress3', models.GenericIPAddressField(blank=True, null=True, verbose_name='Web Sunucusu IP 3')),
                ('ipAddress4', models.GenericIPAddressField(blank=True, null=True, verbose_name='Web Sunucusu IP 4')),
                ('ipAddress5', models.GenericIPAddressField(blank=True, null=True, verbose_name='Web Sunucusu IP 5')),
                ('username', models.CharField(blank=True, max_length=255, null=True, verbose_name='Kullanıcı Adı')),
                ('password', models.CharField(blank=True, max_length=255, null=True, verbose_name='Şifre')),
                ('paymentType', models.CharField(choices=[('Monthly', 'Aylık'), ('Yearly', 'Yıllık')], default='Monthly', max_length=10, verbose_name='Ödeme Tipi')),
                ('priceUsd', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Ücret (USD)')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updatedAt', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('operatingSystem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='soloaccounting.operatingsystem', verbose_name='İşletim Sistemi')),
            ],
            options={
                'verbose_name': 'Web Sunucusu',
                'verbose_name_plural': 'Web Sunucuları',
            },
        ),
    ]
