# Generated by Django 5.1.3 on 2024-12-03 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('soloaccounting', '0005_remove_service_product_remove_service_site_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='extendedsite',
            options={'verbose_name': 'Genişletilmiş Site', 'verbose_name_plural': 'Genişletilmiş Siteler'},
        ),
        migrations.AddField(
            model_name='extendedsite',
            name='isOurSite',
            field=models.BooleanField(default=False, help_text='Bu site bizim tarafımızdan kontrol ediliyorsa işaretleyin.', verbose_name='Bizim Sitemiz'),
        ),
        migrations.AddField(
            model_name='extendedsite',
            name='showPopupAd',
            field=models.BooleanField(default=False, help_text='Bu sitede pop-up reklam göstermek istiyorsanız işaretleyin.', verbose_name='Pop-up Reklam Gösterimi'),
        ),
        migrations.AlterField(
            model_name='extendedsite',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, help_text='Kayıt oluşturulma tarihi otomatik olarak eklenir.', verbose_name='Oluşturulma Tarihi'),
        ),
        migrations.AlterField(
            model_name='extendedsite',
            name='isActive',
            field=models.BooleanField(default=True, help_text='Bu site aktif mi? Aktif olmayan siteler listelerde gösterilmez.', verbose_name='Aktif'),
        ),
        migrations.AlterField(
            model_name='extendedsite',
            name='site',
            field=models.OneToOneField(help_text='Bağlı olduğu siteyi seçin.', on_delete=django.db.models.deletion.CASCADE, related_name='extended_site', to='sites.site', verbose_name='Site'),
        ),
        migrations.AlterField(
            model_name='extendedsite',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True, help_text='Son güncellenme tarihi otomatik olarak eklenir.', verbose_name='Güncellenme Tarihi'),
        ),
    ]
