# Generated by Django 5.1.3 on 2024-11-30 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soloaccounting', '0006_operatingsystem_mailserver_dnsserver_sqlserver_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ürün adını belirtiniz.', max_length=255, unique=True, verbose_name='Ürün Adı')),
                ('description', models.TextField(blank=True, help_text='Ürün ile ilgili açıklama.', null=True, verbose_name='Ürün Açıklaması')),
                ('serviceDuration', models.PositiveIntegerField(help_text='Hizmet süresi ay cinsinden belirtilmelidir.', verbose_name='Hizmet Süresi (Ay)')),
                ('price', models.DecimalField(decimal_places=2, help_text='Ürün fiyatını belirtiniz.', max_digits=10, verbose_name='Ürün Fiyatı')),
                ('isActive', models.BooleanField(default=True, help_text='Ürünün aktif/pasif durumunu belirtir.', verbose_name='Aktif')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updatedAt', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
            ],
            options={
                'verbose_name': 'Ürün',
                'verbose_name_plural': 'Ürünler',
            },
        ),
        migrations.AddField(
            model_name='module',
            name='isActive',
            field=models.BooleanField(default=True, help_text='Modülün aktif/pasif durumunu belirtir.', verbose_name='Aktif'),
        ),
        migrations.AddField(
            model_name='module',
            name='price',
            field=models.DecimalField(decimal_places=2, default='100', help_text='Modül fiyatını belirtiniz.', max_digits=10, verbose_name='Fiyat'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='module',
            name='serviceDuration',
            field=models.PositiveIntegerField(default='12', help_text='Hizmet süresi ay cinsinden belirtilmelidir.', verbose_name='Hizmet Süresi (Ay)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='module',
            name='product',
            field=models.ForeignKey(blank=True, help_text='Bu modüle ait bir ürün seçin (isteğe bağlı).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modules', to='soloaccounting.product', verbose_name='Ürün'),
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Hizmetin adını belirtiniz.', max_length=255, verbose_name='Hizmet Adı')),
                ('description', models.TextField(blank=True, help_text='Hizmet ile ilgili açıklama.', null=True, verbose_name='Hizmet Açıklaması')),
                ('serviceDuration', models.PositiveIntegerField(help_text='Hizmet süresi ay cinsinden belirtilmelidir.', verbose_name='Hizmet Süresi (Ay)')),
                ('price', models.DecimalField(decimal_places=2, help_text='Hizmet fiyatını belirtiniz.', max_digits=10, verbose_name='Hizmet Fiyatı')),
                ('isActive', models.BooleanField(default=True, help_text='Hizmetin aktif/pasif durumunu belirtir.', verbose_name='Aktif')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updatedAt', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('product', models.ForeignKey(blank=True, help_text='Bu hizmete ait bir ürün seçin (isteğe bağlı).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='soloaccounting.product', verbose_name='Ürün')),
            ],
            options={
                'verbose_name': 'Hizmet',
                'verbose_name_plural': 'Hizmetler',
            },
        ),
    ]
