# Generated by Django 5.1.3 on 2024-12-06 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soloaccounting', '0006_alter_extendedsite_options_extendedsite_isoursite_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendedsite',
            name='isDefault',
            field=models.BooleanField(default=False, help_text='Bu site varsayılan olarak seçilsin mi?', verbose_name='Varsayılan Site'),
        ),
    ]
