# Generated by Django 5.1.3 on 2024-12-07 03:02

import soloaccounting.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soloaccounting', '0007_extendedsite_isdefault'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendedsite',
            name='logo',
            field=models.ImageField(default='logos/default_logo.webp', help_text='Site için bir logo yükleyin. Görüntü otomatik olarak 48x48 piksel ve kare formatına uygun hale getirilir.', upload_to=soloaccounting.models.logo_upload_path, verbose_name='Site Logosu'),
        ),
    ]
