# Generated by Django 5.1.3 on 2024-11-30 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('soloaccounting', '0007_product_module_isactive_module_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteUrun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='module', to='sites.site', verbose_name='Site')),
                ('urun', models.ManyToManyField(related_name='siteUrun', to='soloaccounting.product', verbose_name='Ürünler')),
            ],
            options={
                'verbose_name': 'Site Ürün Eşleşmesi',
                'verbose_name_plural': 'Site Ürün Eşleşmeleri',
            },
        ),
        migrations.DeleteModel(
            name='SiteModule',
        ),
    ]
