# Generated by Django 5.1.3 on 2024-12-07 04:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('soloaccounting', '0008_extendedsite_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteurun',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='urunSite', to='sites.site', verbose_name='Site'),
        ),
    ]
