# Generated by Django 5.1.3 on 2024-11-30 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soloaccounting', '0008_siteurun_delete_sitemodule'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dnsserver',
            options={'verbose_name': 'S-DNS Sunucusu', 'verbose_name_plural': 'S-DNS Sunucuları'},
        ),
        migrations.AlterModelOptions(
            name='mailserver',
            options={'verbose_name': 'S-Mail Sunucusu', 'verbose_name_plural': 'S-Mail Sunucuları'},
        ),
        migrations.AlterModelOptions(
            name='operatingsystem',
            options={'verbose_name': 'S-İşletim Sistemi', 'verbose_name_plural': 'S-İşletim Sistemleri'},
        ),
        migrations.AlterModelOptions(
            name='sqlserver',
            options={'verbose_name': 'S-SQL Sunucusu', 'verbose_name_plural': 'S-SQL Sunucuları'},
        ),
        migrations.AlterModelOptions(
            name='webserver',
            options={'verbose_name': 'S-Web Sunucusu', 'verbose_name_plural': 'S-Web Sunucuları'},
        ),
    ]
