# Generated by Django 5.1.3 on 2024-11-30 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soloaccounting', '0009_alter_dnsserver_options_alter_mailserver_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomSiteConfiguration',
        ),
    ]
