# Generated by Django 5.1.3 on 2024-11-30 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('soloaccounting', '0010_delete_customsiteconfiguration'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomSiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updatedAt', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('dnsServer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dnsserver_configurations', to='soloaccounting.dnsserver', verbose_name='DNS Server')),
                ('mailServer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mailserver_configurations', to='soloaccounting.mailserver', verbose_name='Mail Server')),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuration', to='sites.site', verbose_name='Site')),
                ('sqlServer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sqlserver_configurations', to='soloaccounting.sqlserver', verbose_name='SQL Server')),
                ('webServer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='webserver_configurations', to='soloaccounting.webserver', verbose_name='Web Server')),
            ],
            options={
                'verbose_name': 'Site Konfigürasyonu',
                'verbose_name_plural': 'Site Konfigürasyonları',
            },
        ),
    ]
