# Generated by Django 5.1.3 on 2024-12-07 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soloaccounting', '0010_siteurun_updatedate_siteurun_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteurun',
            name='updateDate',
        ),
        migrations.RemoveField(
            model_name='siteurun',
            name='user',
        ),
    ]
