# Generated by Django 5.1.3 on 2024-11-30 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soloaccounting', '0011_customsiteconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='dnsserver',
            name='isActive',
            field=models.BooleanField(default=True, help_text='Sunucunun aktif/pasif durumunu belirtir.', verbose_name='Aktif'),
        ),
        migrations.AddField(
            model_name='dnsserver',
            name='isDefault',
            field=models.BooleanField(default=False, help_text='Bu sunucunun varsayılan olup olmadığını belirtir.', verbose_name='Varsayılan'),
        ),
        migrations.AddField(
            model_name='mailserver',
            name='isActive',
            field=models.BooleanField(default=True, help_text='Sunucunun aktif/pasif durumunu belirtir.', verbose_name='Aktif'),
        ),
        migrations.AddField(
            model_name='mailserver',
            name='isDefault',
            field=models.BooleanField(default=False, help_text='Bu sunucunun varsayılan olup olmadığını belirtir.', verbose_name='Varsayılan'),
        ),
        migrations.AddField(
            model_name='sqlserver',
            name='isActive',
            field=models.BooleanField(default=True, help_text='Sunucunun aktif/pasif durumunu belirtir.', verbose_name='Aktif'),
        ),
        migrations.AddField(
            model_name='sqlserver',
            name='isDefault',
            field=models.BooleanField(default=False, help_text='Bu sunucunun varsayılan olup olmadığını belirtir.', verbose_name='Varsayılan'),
        ),
        migrations.AddField(
            model_name='webserver',
            name='isActive',
            field=models.BooleanField(default=True, help_text='Sunucunun aktif/pasif durumunu belirtir.', verbose_name='Aktif'),
        ),
        migrations.AddField(
            model_name='webserver',
            name='isDefault',
            field=models.BooleanField(default=False, help_text='Bu sunucunun varsayılan olup olmadığını belirtir.', verbose_name='Varsayılan'),
        ),
    ]
