# Generated by Django 5.1.3 on 2024-11-30 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soloaccounting', '0013_customuser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Kullanıcı', 'verbose_name_plural': 'Kullanıcılar'},
        ),
    ]
