# Generated by Django 5.1.3 on 2024-12-07 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soloaccounting', '0013_alter_product_createdate_alter_product_updatedate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='site',
        ),
    ]
