# Generated by Django 5.1.3 on 2024-12-09 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soloaccounting', '0014_remove_customuser_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, help_text="Ürünün URL'de kullanılacak kısa adı. Otomatik oluşturulur.", max_length=255, unique=False, verbose_name='Slug'),
        ),
    ]
