# Generated by Django 5.1.3 on 2024-11-30 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soloaccounting', '0015_customuser_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='digitalMarketingPermission',
            field=models.BooleanField(default=False, verbose_name='Dijital Pazarlama İzni'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='kvkkPermission',
            field=models.BooleanField(default=False, verbose_name='KVKK İzni'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='smsPermission',
            field=models.BooleanField(default=False, verbose_name='SMS İzni'),
        ),
    ]
