# Generated by Django 5.1.3 on 2024-11-30 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soloaccounting', '0016_customuser_digitalmarketingpermission_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='isIndividual',
            field=models.BooleanField(default=True, verbose_name='Kurumsal Fatura İstiyorum'),
        ),
    ]
