# Generated by Django 5.1.3 on 2024-12-09 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soloaccounting', '0016_auto_20241209_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, help_text="Ürünün URL'de kullanılacak kısa adı. Otomatik oluşturulur.", max_length=255, unique=True, verbose_name='Slug'),
        ),
    ]
