# Generated by Django 5.1.3 on 2024-12-09 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soloaccounting', '0017_alter_product_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('path', models.CharField(blank=True, max_length=255, null=True)),
                ('icon', models.CharField(blank=True, help_text="Iconify ikon adı. Örn: 'material-symbols:shopping-cart'", max_length=100, null=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Menü sıralaması')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='soloaccounting.menu')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='soloaccounting.product')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
