# Generated by Django 5.1.3 on 2024-12-09 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soloaccounting', '0018_menu'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ['order'], 'verbose_name': 'Menü Öğesi', 'verbose_name_plural': 'Menü Öğeleri'},
        ),
        migrations.AddField(
            model_name='menu',
            name='caption',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
