# Generated by Django 5.1.3 on 2024-12-10 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soloaccounting', '0019_alter_menu_options_menu_caption'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='disabled',
            field=models.BooleanField(default=False, help_text='Menü öğesinin devre dışı olup olmadığını belirtir'),
        ),
        migrations.AddField(
            model_name='menu',
            name='external',
            field=models.BooleanField(default=False, help_text='Harici bir bağlantı olup olmadığını belirtir'),
        ),
        migrations.AddField(
            model_name='menu',
            name='info',
            field=models.CharField(blank=True, default=None, help_text='Menü öğesi için bilgi (örneğin bir etiket)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='menu',
            name='is_superuser_only',
            field=models.BooleanField(default=False, help_text='Bu menü yalnızca superuser tarafından görülebilir.'),
        ),
        migrations.AddField(
            model_name='menu',
            name='roles',
            field=models.JSONField(blank=True, default=list, help_text="Bu menüye erişimi olan roller listesi. Örn: ['admin', 'manager']", null=True),
        ),
    ]
