# Generated by Django 5.1.3 on 2024-12-10 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soloaccounting', '0020_menu_disabled_menu_external_menu_info_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='roles',
        ),
    ]
