# Generated by Django 5.1.3 on 2024-12-10 09:41

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soloaccounting', '0021_remove_menu_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='roles',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, help_text="Bu menüye erişimi olan roller listesi. Örn: ['admin', 'manager']", null=True, size=None),
        ),
    ]
