# Generated by Django 5.1.3 on 2024-12-11 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soloaccounting', '0022_menu_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='dealerID',
            field=models.IntegerField(blank=True, null=True, verbose_name='Bayi ID'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='discountRate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='İskonto Oranı'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='isDealer',
            field=models.BooleanField(default=False, verbose_name='Bayi Mi?'),
        ),
    ]
